# Generated by Django 5.1.4 on 2025-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='ano_fundacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
