# Generated by Django 5.1.4 on 2025-01-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidade',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
