# Generated by Django 5.1.4 on 2025-01-20 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_universidade_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('HUMANAS', 'Humanas'), ('EXATAS', 'Exatas'), ('BIOLÓGICAS', 'Biológicas'), ('SAÚDE', 'Saúde')], max_length=200)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='ofertas.universidade')),
            ],
        ),
    ]
