# Generated by Django 5.1.4 on 2025-01-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='universidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='ofertas.universidade'),
        ),
    ]
