# Generated by Django 5.1.4 on 2025-01-21 00:01

import ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_alter_curso_universidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidade',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[ofertas.models.tamanho_sigla]),
        ),
    ]
